remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Yuelai Mollie Feng
position: Research Technician
affiliation: JazLab @ MIT McGovern
affiliation_link: https://jazlab.org/
email: yuelaif (at) mit.edu

# Search Engine Optimization (SEO)
keywords: yuelai feng, mollie feng
description: Yuelai (Mollie) Feng's personal website.
canonical: https://yuelai-feng.github.io

# Links 
google_scholar: https://scholar.google.com/citations?user=Dn6bwtwAAAAJ&hl=en&authuser=2&oi=ao
github_link: https://github.com/yuelai-feng
linkedin: https://www.linkedin.com/in/yuelai-feng/

# Images (e.g., your profile picture and your website's favicon) 
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true